[database]
host = "mysql"
database = "nodelab"
username = "nodelab"
password = "test"

[context]
timeout = 2

[logging]
logLevel = "debug"
sentryDSN = "https://f3ad1bf0dd4e4aa0bf6b120772dbf9cc@o474972.ingest.sentry.io/5512231"

[phase]
level = "local"