on:
  push:
    branches:
      - feature/25-ecs-cd

name: Deploy to Amazon ECS Development

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nodelab-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -f production.dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      - uses: marocchino/setup-ecs-cli@v1
        with:
          version: "v1.18.0"
      - name: ECS Deploy
        env:
          PHASE: development
          CPU_LIMIT: 512
          MEM_LIMIT: 1024
          CONTAINER_PORT: 9090
          TASK_EXECUTION_ROLE_ARN: ${{ secrets.TASK_EXECUTION_ROLE_ARN }}
          TARGET_GROUP_ARN: ${{ secrets.TARGET_GROUP_ARN }}
          SSM_ARN: ${{ secrets.SSM_ARN }}
          SUBNET_1: ${{ secrets.SUBNET_1 }}
          SUBNET_2: ${{ secrets.SUBNET_2 }}
          IMAGE: ${{ steps.build-image.outputs.image }}
        run: |
           ecs-cli compose --cluster nodelab-dev-fargate \
            service up \
            --launch-type FARGATE \
            --target-group-arn $TARGET_GROUP_ARN \
            --container-name api \
            --container-port $CONTAINER_PORT
